name: Upload test.m to Artifactory

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch
env:
  CADENV_HOME: ${{ github.WORKSPACE}}/caddir
  
jobs:
  upload-to-artifactory:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload test.m to Artifactory
      env:
        ARTIFACTORY_URL: https://trialebic7z.jfrog.io/artifactory/matlab_files-generic-local/
        ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}  # Add your Artifactory API key as a GitHub secret
      run: |
        # Upload the file using curl
        for file in p_files/*; do
          curl -u ":$ARTIFACTORY_API_KEY" -T "$file" "$ARTIFACTORY_URL$(basename "$file")"
        done
